TARGET =	hw4
LIBS =		-lsimple -lcheck -lsuif -luseful
OBJS =		doproc.o main.o basicblk.o natloop.o dfa.o cfg.o procedure.o program.o 

all:            $(TARGET)
install-bin:    install-prog

include $(SUIFHOME)/Makefile.std

