TARGET =	hw4
LIBS =		-lsimple -lcheck -lsuif -luseful
OBJS =		doproc.o main.o basicblk.o natloop.o dfa.o cfg.o procedure.o program.o reaching_definition.o use_def.o print.o

all:            $(TARGET)
install-bin:    install-prog

include $(SUIFHOME)/Makefile.std

